---
version: "2"
services:
  organizr:
    container_name: rpi-monitor
    image: michaelmiklis/rpi-monitor:latest
    restart: unless-stopped
    devices:
      - /dev/vchiq
      - /dev/vcsm
    ports:
        - 8888:8888
    volumes:
        - /opt/vc:/opt/vc
        - /sys:/dockerhost/sys:ro
        - /etc:/dockerhost/etc:ro
        - /proc:/dockerhost/proc:ro
        - /usr/lib:/dockerhost/usr/lib:ro

# docker run --device=/dev/vchiq --device=/dev/vcsm --volume=/opt/vc:/opt/vc --volume=/boot:/boot --volume=/sys:/dockerhost/sys:ro --volume=/etc:/dockerhost/etc:ro --volume=/proc:/dockerhost/proc:ro --volume=/usr/lib:/dockerhost/usr/lib:ro -p=8888:8888 --name="rpi-monitor" -d  michaelmiklis/rpi-monitor:latest