version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /srv/dev-disk-by-label-media/configs/influx/db:/var/lib/influxdb2:rw
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    # env_file:
    #   - 'env.influxdb'
  # Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /srv/dev-disk-by-label-media/configs/influx/db:/var/lib/influxdb2:rw
      # - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      # - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=antau
      - DOCKER_INFLUXDB_INIT_PASSWORD=psw
      - DOCKER_INFLUXDB_INIT_ORG=homehub
      - DOCKER_INFLUXDB_INIT_BUCKET=homehub_bucket
      
    # entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    # env_file:
    #   - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      - /srv/dev-disk-by-label-media/configs/grafana/data:/var/lib/grafana
    
volumes:
  influxdb2: