version: '3'
services:
  grafana:
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=$SERVICE_USER
      - GF_SECURITY_ADMIN_PASSWORD=$SERVICE_PASSWORD
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "1000"
    ports:
      - '3000:3000'
    volumes:
      - $APPDATADIR/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro