version: '3'
services:
  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8083:80"

secrets:
  pgadmin-secret:
    file: /mnt/user/appdata/secrets/pgadmin-secret