version: '3.3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=NL
    #   - PLEX_CLAIM=<claimToken>
    network_mode: host
    volumes:
      - /mnt/user/appdata/plex:/config
      - /mnt/user/data/media/series:/tv
      - /mnt/user/data/media/movies:/movies
      - /mnt/user/data/app/plex:/data
      - /mnt/user/data/app/transcode:/transcode
    devices:
      - /dev/dri:/dev/dri
    privileged: true
