version: '3'
services:
  app:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "media_db"
      DB_MYSQL_PASSWORD: "Q3yUU83WFM62"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /srv/dev-disk-by-label-media/configs/nginx/data:/data
      - /srv/dev-disk-by-label-media/configs/nginx/letsencrypt:/etc/letsencrypt
      - /srv/dev-disk-by-label-media/configs/nginx/etc:/etc/nginx
  certbot:
    image: certbot/certbot
  
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '3vipTMYjVRqBJ'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'media_db'
      MYSQL_PASSWORD: 'Q3yUU83WFM62'
    volumes:
      - /srv/dev-disk-by-label-media/configs/nginx/data/mysql:/var/lib/mysql