version: '3'
services:
  mosquitto_broker:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ~/homehub_config/mosquitto/data:/mosquitto/data 
      - ~/homehub_config/mosquitto/log:/mosquitto/log
      - ~/homehub_config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf 
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam

      
