services:
  mosquitto_broker:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.22
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ~/config/mosquitto/data:/mosquitto/data
      - ~/config/mosquitto/log:/mosquitto/log
      - ~/config/mosquitto/config:/mosquitto/config
    restart: always
    environment:
      - TZ=Europe/Amsterdam
