version: '3'
services:
  zigbee2mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - /home/pi/config/mosquitto/data:/mosquitto/data 
      - /home/pi/config/mosquitto/log:/mosquitto/log
      - /home/pi/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf 
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam

      
