version: '3.1'
services:
  deconz:
    container_name: deconz
    image: marthoc/deconz
    restart: always
    network_mode: host
    volumes:
      - /home/pi/config/deCONZ:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0
    environment:
      # - DECONZ_WEB_PORT=80
      # - DECONZ_WS_PORT=443
      # - DEBUG_INFO=1
      # - DEBUG_APS=0
      # - DEBUG_ZCL=0
      # - DEBUG_ZDP=0
      # - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyACM0