version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mysql
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /srv/dev-disk-by-label-media/configs/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=J6uYvM3cn43nmT
      - MYSQL_PASSWORD=wyCecgV9dT4p86
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - /srv/dev-disk-by-label-media/cloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=wyCecgV9dT4p86
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db